DELETE FROM `categoriaproducto` ;
ALTER TABLE `categoriaproducto` AUTO_INCREMENT = 0;
/*86*/
INSERT INTO `categoriaproducto` (`IdCategoria`, `Nombre`, `IdTipo`) VALUES
(1, 'Bebidas y jugos', 1),
(2, 'Cecinas', 1),
(3, 'Carnes procesadas', 1),
(4, 'Golosinas: caramelos, gomitas, otros', 1),
(5, 'Helados', 1),
(6, 'Hamburguesas', 1),
(7, 'Harinas, almidones y premezclas', 1),
(8, 'Productos horneados y Pastelería', 1),
(9, 'Galletas ', 1),
(10, 'Otras leches', 1),
(11, 'Productos para repostería y panificación', 1),
(12, 'Pastas', 1),
(13, 'Postres', 1),
(14, 'Snack', 1),
(15, 'Suplementos alimentarios', 1),
(16, 'Endulzante ', 1),
(17, 'Galletas, panes, horneados en general', 1),
(18, 'Cereales para desayuno y barras de cereal', 1),
(20, 'Pastas y fideos', 1),
(21, 'Conservas', 1),
(22, 'Alimentos para regímenes especiales', 1),
(23, 'Productos lácteos', 1),
(24, 'Chocolates y caramelos', 1),
(25, 'Ingredientes especiales', 1),
(26, 'Sopas y cremas', 1),
(27, 'Postres y  helados', 1),
(28, 'Leches vegetales', 1),
(29, 'Frutos secos - liofilizada', 1),
(30, 'Otros ', 1),
(31, 'Licores', 1),
(32, 'Jugos y bebidas', 1),
(33, 'Salsas y aliños', 1),
(34, 'Lácteos', 1),
(35, 'Mermelada', 1),
(36, 'Galletas y colaciones ', 1),
(37, 'Harinas y almidones ', 1),
(38, 'Productos horneados ', 1),
(39, 'Productos de uso personal', 2),
(40, 'Antimicótico de amplio espectro', 2),
(41, 'Analgésico. Relajante muscular', 2),
(42, 'Antagonista del calcio. Antiarrítmico. Hipotensor', 2),
(43, 'Antialérgico. Antihistamínico', 2),
(44, 'Antialérgico. Antihistamínico. Descongestivo', 2),
(45, 'Antianginoso. Vasodilatador coronario', 2),
(46, 'Antiarrítmico', 2),
(47, 'Antibiótico tetraciclínico de amplio espectro', 2),
(48, 'Anticonvulsivante Benzodiazepínico. Tranquilizante. Ansiolítico', 2),
(49, 'Anticonvulsivantes Antiepilépticos ', 2),
(50, 'Antidepresivo', 2),
(51, 'Antidiarreico ecológico', 2),
(52, 'Antigripal. Analgésico. Descongestionante', 2),
(53, 'Antihipertensivo. Diurético. Tratamiento de la insuficiencia cardíaca', 2),
(54, 'Antihistamínico. Descongestivo nasal. Corticoterapia asociada', 2),
(55, 'Antinflamatorio no esteroide. Analgésico. Antirreumático', 2),
(56, 'Antinflamatorio. Antipirético', 2),
(57, 'Antijaquecoso. Antimigrañosos', 2),
(58, 'Antirreumático, analgésico y antiflogístico con inhibición preferencial de la forma inducible de la enzima ciclooxigenasa (COX-2)', 2),
(59, 'Antiséptico bucofaríngeo', 2),
(60, 'Antitusivo. Descongestivo', 2),
(61, 'Antivertiginoso, Antiemético', 2),
(62, 'Antiulceroso', 2),
(63, 'Betabloqueador b1-selectivo', 2),
(64, 'Bloqueador de los canales del calcio', 2),
(65, 'Estimulante de acción central', 2),
(66, 'Cerebrotónico', 2),
(67, 'Expectorante. Antitusivo. Broncoespasmolítico', 2),
(68, 'Farmacoterapia de la hiperplasia prostática benigna', 2),
(69, 'Farmacoterapia del acné', 2),
(70, 'Glucocorticoide. Antinflamatorio. Antirreumático. Antialérgico', 2),
(71, 'Hipoglucemiante', 2),
(72, 'Hipoglicemiante. Antihiperglicemiante', 2),
(73, 'Hipolipemiante', 2),
(74, 'Hormonoterapia tiroidea', 2),
(75, 'Metabolismo Óseo', 2),
(76, 'Miorrelajante. Sedante', 2),
(77, 'Neuroprotector. Reactivador de las funciones psíquicas y motoras', 2),
(78, 'Neuroprotector. Procolinérgico', 2),
(79, 'Procinético-antiemético', 2),
(80, 'Suplementación de una dieta diaria subóptima con bacterias de ácido láctico, vitaminas, minerales y oligoelementos', 2),
(81, 'Suplemento de apoyo al climaterio', 2),
(82, 'Suplemento de calcio y vitamina D oral', 2),
(83, 'Suplemento vitamínico. Polivitamínico con minerales. Antioxidante', 2),
(84, 'Terapia de sustitución tiroidea', 2),
(85, 'Vitamina D3', 2),
(86, 'Suplemento Nutricional', 2),
(87, 'Sin Categoría ', 1),
(88, 'Sin Categoría ', 2);