
CREATE TABLE `provincia` (
  `IdProvincia` int(11) NOT NULL COMMENT 'ID provincia',
  `IdRegion` int(11) NOT NULL COMMENT 'ID region asociada',
  `Nombre` varchar(30) COLLATE latin1_spanish_ci NOT NULL COMMENT 'Nombre descriptivo',
  PRIMARY KEY (`IdProvincia`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci COMMENT='Lista de comunas por regiones';

INSERT INTO `provincia` VALUES 	(1,1,'ARICA'),
									(2,1,'PARINACOTA'),
									(3,2,'IQUIQUE'),
									(4,2,'TAMARUGAL'),
									(5,3,'ANTOFAGASTA'),
									(6,3,'EL LOA'),
									(7,3,'TOCOPILLA'),
									(8,4,'COPIAPÓ'),
									(9,4,'CHAÑARAL'),
									(10,4,'HUASCO'),
									(11,5,'ELQUI'),
									(12,5,'CHOAPA'),
									(13,5,'LIMARÍ'),
									(14,6,'VALPARAÍSO'),
									(15,6,'ISLA DE PASCUA'),
									(16,6,'LOS ANDES'),
									(17,6,'PETORCA'),
									(18,6,'QUILLOTA'),
									(19,6,'SAN ANTONIO'),
									(20,6,'SAN FELIPE DE ACONCAGUA'),
									(21,6,'MARGA MARGA'),
									(22,7,'CACHAPOAL'),
									(23,7,'CARDENAL CARO'),
									(24,7,'COLCHAGUA'),
									(25,8,'TALCA'),
									(26,8,'CAUQUENES'),
									(27,8,'CURICÓ'),
									(28,8,'LINARES'),
									(29,9,'CONCEPCIÓN'),
									(30,9,'ARAUCO'),
									(31,9,'BIOBÍO'),
									(32,9,'ÑUBLE'),
									(33,10,'CAUTÍN'),
									(34,10,'MALLECO'),
									(35,11,'VALDIVIA'),
									(36,11,'RANCO'),
									(37,12,'LLANQUIHUE'),
									(38,12,'CHILOÉ'),
									(39,12,'OSORNO'),
									(40,12,'PALENA'),
									(41,13,'COIHAIQUE'),
									(42,13,'AISÉN'),
									(43,13,'CAPITÁN PRAT'),
									(44,13,'GENERAL CARRERA'),
									(45,14,'MAGALLANES'),
									(46,14,'ANTÁRTICA CHILENA'),
									(47,14,'TIERRA DEL FUEGO'),
									(48,14,'ULTIMA ESPERANZA'),
									(49,15,'SANTIAGO'),
									(50,15,'CORDILLERA'),
									(51,15,'CHACABUCO'),
									(52,15,'MAIPO'),
									(53,15,'MELIPILLA'),
									(54,15,'TALAGANTE');