CREATE TABLE `log_producto` (
  `IdMovimiento` int(11) NOT NULL AUTO_INCREMENT,
  `IdProducto` int(11) NOT NULL,
  `Descripcion` varchar(8000) NOT NULL,
  `IdTipo` int(11) NOT NULL,
  `IdSubcategoria` int(11) NOT NULL,
  `IdEmpresa` int(11) NOT NULL,
  `IdCategoria` int(11) NOT NULL,
  `IdEstadoCertificacion` int(11) NOT NULL,
  `UsuarioModifica` varchar(200) DEFAULT 'anonymous',
  `FechaModificacion` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Accion` varchar(50) DEFAULT NULL,
   PRIMARY KEY (`IdMovimiento`),
  KEY `IdTipo_log1` (`IdTipo`),
  KEY `IdSubcategoria_log1` (`IdSubcategoria`),
  KEY `IdEmpresa_log1` (`IdEmpresa`),
  KEY `IdCategoria_log1` (`IdCategoria`),
  KEY `IdEstadoCertificacion_log` (`IdEstadoCertificacion`),
  CONSTRAINT `producto_ibfk_1_log1` FOREIGN KEY (`IdTipo`) REFERENCES `tipoproducto` (`IdTipo`),
  CONSTRAINT `producto_ibfk_2_log1` FOREIGN KEY (`IdSubcategoria`) REFERENCES `subcategoriaproducto` (`IdSubcategoria`),
  CONSTRAINT `producto_ibfk_3_log1` FOREIGN KEY (`IdEmpresa`) REFERENCES `empresa` (`IdEmpresa`),
  CONSTRAINT `producto_ibfk_4_log1` FOREIGN KEY (`IdCategoria`) REFERENCES `categoriaproducto` (`IdCategoria`),
  CONSTRAINT `producto_ibfk_5_log1` FOREIGN KEY (`IdEstadoCertificacion`) REFERENCES `estadocertificacion` (`IdEstadoCertificacion`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
